name: nexstar
description: Nexstar astronomy protocol command factory and parser.
version: 0.0.2
repository: https://github.com/spin7ion/nexstar_flutter

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.6.0

dependencies:
  sprintf: "^7.0.0"

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
